### ISSUE TITLE
npm install failure

### ISSUE THREAD

**Issue by haydenjames** [Mastermindzh/tidal-hifi#24]
Here's the tail output of npm install:
```
1806 silly saveTree └── request@2.88.2
1807 warn tidal-hifi@1.0.1 No repository field.
1808 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.1 (node_modules/fsevents):
1809 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
1810 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
1810 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
1810 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
1810 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: arm64
1811 verbose stack Error: electron@git+https://github.com/castlabs/electron-releases.git#c36e1ad778fa42ca8a558216dc7be52bb8b11c40 postinstall: `node install.js`
1811 verbose stack Exit status 1
1811 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
1811 verbose stack     at EventEmitter.emit (events.js:314:20)
1811 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
1811 verbose stack     at ChildProcess.emit (events.js:314:20)
1811 verbose stack     at maybeClose (internal/child_process.js:1047:16)
1811 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
1812 verbose pkgid electron@git+https://github.com/castlabs/electron-releases.git#c36e1ad778fa42ca8a558216dc7be52bb8b11c40
1813 verbose cwd /home/hydn/tidal-hifi
1814 verbose Linux 5.8.10-2-MANJARO-ARM
1815 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
1816 verbose node v14.11.0
1817 verbose npm  v6.14.7
1818 error code ELIFECYCLE
1819 error errno 1
1820 error electron@git+https://github.com/castlabs/electron-releases.git#c36e1ad778fa42ca8a558216dc7be52bb8b11c40 postinstall: `node install.js`
1820 error Exit status 1
1821 error Failed at the electron@git+https://github.com/castlabs/electron-releases.git#c36e1ad778fa42ca8a558216dc7be52bb8b11c40 postinstall script.
1821 error This is probably not a problem with npm. There is likely additional logging output above.
1822 verbose exit [ 1, true ]
```

```
                             OS: Manjaro-ARM 20.10
                             Kernel: aarch64 Linux 5.8.10-2-MANJARO-ARM
         #####               Uptime: 35m
        #######              Packages: Unknown
        ##O#O##              Shell: bash 5.0.18
        #######              Resolution: 1920x1080
      ###########            WM: i3
     #############           GTK Theme: Adapta-Nokto-Eta-Maia [GTK2/3]
    ###############          Icon Theme: ePapirus
    ################         Font: Noto Sans 12
   #################         Disk: 9.4G / 60G (17%)
 #####################       CPU: Unknown @ 6x 1.416GHz
   #################         RAM: 2826MiB / 3795MiB

```

**Comment by Mastermindzh** [comment]
I'm afraid the software will not run on ARM.
A core dependency of the "Castlabs Electron" is to have an x86 OS.

Sorry that I can't be of much help.


PS: love the tux.
