### ISSUE TITLE
Playback bug

### ISSUE THREAD

**Issue by rexjohannes** [Mastermindzh/tidal-hifi#246]
After exactly 20 seconds, the playback pauses and shows the following message:

![image](https://github.com/Mastermindzh/tidal-hifi/assets/53578137/98be4312-f895-4cb5-94ee-9e89fedcf172)

I'm running the latest version on Windows. Using HiFi quality audio with the HiFi subscription. But the same on High quality audio.

In the console, the following message gets spammed:

app.384e8e58febaf212b9e8.js:1 POST https://listen.tidal.com/v1/drm/licenses/widevine?token=[redacted token] 400
164 C:\Users\Johannes\AppData\Local\Programs\tidal-hifi\resources\app.asar\ts-dist\preload.js:104 Uncaught TypeError: Cannot read properties of null (reading 'closest')
    at Object.getAlbumName (C:\Users\Johannes\AppData\Local\Programs\tidal-hifi\resources\app.asar\src\preload.ts:108:70)
    at C:\Users\Johannes\AppData\Local\Programs\tidal-hifi\resources\app.asar\src\preload.ts:407:26
getAlbumName @ VM164 C:\Users\Johannes\AppData\Local\Programs\tidal-hifi\resources\app.asar\ts-dist\preload.js:104
(anonymous) @ VM164 C:\Users\Johannes\AppData\Local\Programs\tidal-hifi\resources\app.asar\ts-dist\preload.js:370

the widevine request returns the following error:

{
  "status": 400,
  "subStatus": 999,
  "userMessage": "DRM request failed."
}

**Comment by rexjohannes** [comment]
https://github.com/Mastermindzh/tidal-hifi/issues/238
