### ISSUE TITLE
Discord presence doesn't update after the first song.

### ISSUE THREAD

**Issue by flexcrush420** [Mastermindzh/tidal-hifi#512]
Hey there and thanks for this btw,

When I open discord (installed via deb package not flatpack), and tidal-hifi, the first song appears in my activity/discord presence, but after the song ends it doesn't ever update to the new song.  Any tips?

**Comment by Mastermindzh** [comment]
Will debug when I have the time :)

**Comment by Mastermindzh** [comment]
I can't reproduce this for the life of me :/
Any updates?

**Comment by SinnerK0N** [comment]
I am having the same issue but it doesn't seem to be related to the "Show Idle Text" option.

Here is what I have noticed:
The first song played works, when paused it either hides the RPC or shows that I'm browsing Tidal. When the first song ends, it gets stuck at the end timestamp on Discord and doesn't update. When the first song is skipped, it appears as if it was playing on Discord. When it "finishes playing" on Discord it also gets stuck at the end timestamp. Pausing from this point on doesn't do anything with the rich presence. The only way to update the rich presence again is to manually start playing a different song. Turning off and then back on the option to show Discord RPC in the settings doesn't help.

**Comment by flexcrush420** [comment]
That's just like the issue I was experiencing.
Try reinstalling it, don't change any settings, and see if it just works, if it does, you'll know it was a setting you changed. Just tested mine and it works fine though I didn't change much from the default settings. Also I'm not using flatpak discord but the deb package from the discord site.

-------- Original Message --------

**Comment by M4ST3R0FD1S4ST3R** [comment]
Happening for me to on Solus Linux but won't even display the first song played: 
`(node:51493) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14)
(node:51493) UnhandledPromiseRejectionWarning: UNKNOWN_ERROR: Unknown Error
    at ClientUser.setActivity (/nix/store/bkdhyhxyjswjpiav9sahvdbzkgdh7fv8-tidal-hifi-5.17.0/opt/tidal-hifi/resources/app.asar/node_modules/@xhayper/discord-rpc/dist/structures/ClientUser.js:215:35)
    at updateActivity (/nix/store/bkdhyhxyjswjpiav9sahvdbzkgdh7fv8-tidal-hifi-5.17.0/opt/tidal-hifi/resources/app.asar/ts-dist/scripts/discord.js:44:73)
    at IpcMainImpl.observer (/nix/store/bkdhyhxyjswjpiav9sahvdbzkgdh7fv8-tidal-hifi-5.17.0/opt/tidal-hifi/resources/app.asar/ts-dist/scripts/discord.js:28:9)
    at IpcMainImpl.emit (node:events:529:35)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:87575)
    at WebContents.emit (node:events:517:28)
`
Also running with the flag the error output is recommending "--unhandled-rejections=strict" throws out the same error
